---
Name: more-admins
After:
  - 'framework/*'
  - 'cms/*'
---
Controller:
  extensions:
    - MoreAdminsController
Injector:
  MemberLoginForm:
    properties:
      authenticator_class: MoreAdminsAuthenticator
  RequestProcessor:
    properties:
      filters:
        - %$MoreAdminsRequestFilter